# Generated by Django 2.2 on 2019-09-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=128)),
                ('email_password', models.CharField(max_length=64)),
                ('smtp_server', models.CharField(max_length=128)),
                ('default_reminder_email', models.CharField(max_length=255)),
            ],
        ),
    ]
