# Generated by Django 2.2 on 2019-09-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='smtp_port',
            field=models.IntegerField(default=443),
            preserve_default=False,
        ),
    ]
