# Generated by Django 2.2 on 2019-09-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_config_ddc_reminder_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='conn_account',
            field=models.CharField(default='admin', max_length=255),
        ),
        migrations.AddField(
            model_name='config',
            name='conn_password',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='config',
            name='server_domain',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='config',
            name='server_ip',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='config',
            name='server_port',
            field=models.IntegerField(default=8080),
        ),
    ]
