# Generated by Django 2.2 on 2019-09-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_config_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='speeding_threshold',
            field=models.FloatField(default=80.0),
        ),
    ]
