# Generated by Django 2.2 on 2019-09-02 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('bus', 'Bus'), ('earth-mover', 'Earth Moving Equipment')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reminder_type', models.CharField(choices=[('service', 'Vehicle Service'), ('certificate-of-fitness', 'Vehicle Certificate of Fitness')], max_length=64)),
                ('interval_days', models.IntegerField(default=180)),
                ('interval_mileage', models.IntegerField(default=5000)),
                ('reminder_email', models.EmailField(max_length=254)),
                ('reminder_message', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.Vehicle')),
            ],
        ),
    ]
