# Generated by Django 2.2 on 2019-09-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='last_reminder',
            field=models.DateField(blank=True, null=True),
        ),
    ]
