# Generated by Django 2.2 on 2019-09-16 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reminder_last_reminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_names', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=16)),
                ('address', models.TextField(blank=True)),
                ('license_number', models.CharField(blank=True, max_length=16)),
                ('license_issuing_date', models.DateField(blank=True, null=True)),
                ('license_class', models.IntegerField(blank=True, default=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='driver_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('author', models.CharField(max_length=32)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReminderCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('repeat_method', models.PositiveSmallIntegerField(choices=[(0, 'Never'), (1, 'After an Interval of Time'), (2, 'After a given Mileage'), (3, 'Whichever comes first')])),
                ('frequency_time', models.IntegerField()),
                ('interval_mileage', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='loading_capacity_tons',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='make',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='reports.ReminderCategory'),
        ),
        migrations.CreateModel(
            name='VehicleServiceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('odometer', models.IntegerField()),
                ('vendor', models.CharField(max_length=255)),
                ('notes', models.ManyToManyField(to='reports.Note')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.VehicleService')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=255)),
                ('coverage', models.CharField(choices=[('comprehensive', 'Comprehensive'), ('third-party', 'Third Party')], max_length=32)),
                ('valid_until', models.DateField()),
                ('notes', models.ManyToManyField(to='reports.Note')),
                ('vehicles', models.ManyToManyField(to='reports.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('report', models.FileField(blank=True, null=True, upload_to='incident_reports/')),
                ('number_of_vehicles_involved', models.IntegerField(default=0)),
                ('number_of_pedestrians_involved', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='notes',
            field=models.ManyToManyField(to='reports.Note'),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicles',
            field=models.ManyToManyField(to='reports.Vehicle'),
        ),
        migrations.CreateModel(
            name='DDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField()),
                ('number', models.CharField(blank=True, max_length=16)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Driver')),
            ],
        ),
        migrations.AddField(
            model_name='reminder',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.Driver'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='notes',
            field=models.ManyToManyField(to='reports.Note'),
        ),
    ]
