# Generated by Django 2.2 on 2019-09-16 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20190916_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCertificateOfFitness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('valid_until', models.DateField()),
                ('notes', models.ManyToManyField(to='reports.Note')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='DriverMedical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('valid_until', models.DateField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Driver')),
                ('notes', models.ManyToManyField(to='reports.Note')),
            ],
        ),
    ]
