# Generated by Django 2.2 on 2019-09-17 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20190917_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='vehicles',
        ),
        migrations.AddField(
            model_name='insurance',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reports.Vehicle'),
            preserve_default=False,
        ),
    ]
