# Generated by Django 2.2 on 2019-09-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20190917_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleservice',
            name='date',
        ),
    ]
