# Generated by Django 2.2 on 2019-09-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_remove_vehicleservice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='device_id',
            field=models.CharField(default=100, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_id',
            field=models.CharField(default=200, max_length=64),
            preserve_default=False,
        ),
    ]
