# Generated by Django 2.2 on 2019-10-01 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20190922_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.Driver'),
        ),
    ]
