# Generated by Django 2.2 on 2019-10-04 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_alarm'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='last_reminder_mileage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminder_method',
            field=models.PositiveSmallIntegerField(choices=[(0, 'After an Inteval of Time'), (1, 'After a stated mileage')], default=0),
        ),
    ]
