# Generated by Django 2.2 on 2019-11-19 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_auto_20191006_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='reminder_method',
        ),
        migrations.AddField(
            model_name='reminder',
            name='repeat_after_days',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reminder',
            name='repeat_after_mileage',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ReminderEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('days_before', models.IntegerField(verbose_name=0.0)),
                ('mileage', models.FloatField(default=0.0)),
                ('event_type', models.PositiveSmallIntegerField(choices=[(0, 'Date'), (1, 'Days Before'), (2, 'Mileage')], default=0)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Reminder')),
            ],
        ),
    ]
