# Generated by Django 2.2 on 2019-11-20 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_auto_20191119_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Driver'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Vehicle'),
        ),
        migrations.AlterField(
            model_name='reminderevent',
            name='days_before',
            field=models.IntegerField(default=0.0),
        ),
    ]
