# Generated by Django 2.2 on 2019-11-23 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_auto_20191120_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeatable', models.BooleanField(default=False)),
                ('reminder_email', models.EmailField(max_length=254)),
                ('reminder_message', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('repeat_interval_days', models.IntegerField(default=180)),
                ('last_reminder_date', models.DateField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Driver')),
                ('reminder_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='reports.ReminderCategory')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CalendarReminderAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.PositiveSmallIntegerField(choices=[(0, 'Date'), (1, 'Days Before')], default=0)),
                ('date', models.DateField(blank=True, null=True)),
                ('days', models.IntegerField(default=0.0)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.CalendarReminder')),
            ],
        ),
        migrations.CreateModel(
            name='MileageReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeatable', models.BooleanField(default=False)),
                ('reminder_email', models.EmailField(max_length=254)),
                ('reminder_message', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('repeat_interval_mileage', models.IntegerField(default=5000)),
                ('last_reminder_mileage', models.IntegerField(default=0)),
                ('reminder_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='reports.ReminderCategory')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MileageReminderAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.FloatField(default=0.0)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.MileageReminder')),
            ],
        ),
        migrations.RemoveField(
            model_name='reminderevent',
            name='reminder',
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
        migrations.DeleteModel(
            name='ReminderEvent',
        ),
    ]
