# Generated by Django 2.2 on 2019-11-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_auto_20191123_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='mileagereminder',
            name='mileage',
            field=models.IntegerField(default=5000),
        ),
    ]
