# Generated by Django 2.2 on 2019-11-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_mileagereminder_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mileagereminder',
            name='reminder_count',
            field=models.IntegerField(default=0),
        ),
    ]
